import Link from "next/link";
import "../globals.css";

export const metadata = {
  title: "Admin Panel",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex">
          <div className="w-1/3 bg-teal-200">
           <Link href={'/admin'}><h1>Dashboard</h1></Link> 
           <Link href={'/admin/products'}><h1>Products</h1></Link> 
           <Link href={'/admin/categories'}><h1>Categories</h1></Link> 
          </div>
          <div className="w-2/3 bg-fuchsia-300">{children}</div>
        </div>
      </body>
    </html>
  );
}
