import localFont from "next/font/local";
import "./globals.css";
import { Button } from "@/components/ui/button";
import NavbarMenu from "@/components/NavbarMenu";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ui/therme-toogle";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        >
        <div className={"flex justify-between items-center p-4"}>
          <img src={"./favicon.ico"} className="h-5 w-5" />
          <NavbarMenu />
          <ModeToggle/>
        </div>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
