import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex">
          <div className="w-1/3 bg-teal-200"></div>
          <div className="w-2/3 bg-fuchsia-300">{children}</div>
        </div>
      </body>
    </html>
  );
}
